name: pre-commit
on:
  pull_request:
  push:
    branches: [main]
env:
  CARGO_TERM_COLOR: always
  LIBTORCH_USE_PYTORCH: 1
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: Swatinem/rust-cache@v2
      - uses: awalsh128/cache-apt-pkgs-action@latest
        with:
          packages: libpam0g-dev
          version: 1.0
          execute_install_scripts: true
      - run: sudo apt install -y libopencv-dev
      - uses: actions/setup-python@v5
        with:
          python-version: '3.x'
          cache: 'pip'
      - run: pip install -r requirements.txt
      - uses: pre-commit/action@v3.0.1
